### ISSUE TITLE
Orca Slicer Profile recognized as Trojan script

### ISSUE THREAD

**Issue by Techonrye** [cheadrian/kobra2neo-klipper#1]
When I attempted to get the orca slicer profile for the K2Neo  I was flagged as Trojan:Script/Wacatac.B!ml

**Comment by cheadrian** [comment]
There's no executable in this repo.

You might get a really strange false-positive - [VirusTotal](https://www.virustotal.com/gui/file/cfabc69b0e4835aa411c41a4c73065c6913d21c0031e2fe7ae1b2d938d943271).
