### ISSUE TITLE
Will this setup work on the dedicated UART port for Raspberry PI 5?

### ISSUE THREAD

**Issue by matthewmatician** [cheadrian/kobra2neo-klipper#3]
Hi, 

I am wanting to connect to the raspberry PI 5 using the dedicated UART port. I believe it would connect over UART10 instead of UART0. Can I use your setup to do this? Or is there a way to modify what you have to make that happen?

Thanks!

**Comment by cheadrian** [comment]
It should work. Worst case you have to change UART config on RPi5 till you match the supported one.
Search on how to enable the `/dev/ttyAMA0` for Pi5 and compatible GPIO.

https://forums.raspberrypi.com/viewtopic.php?t=362821

**Comment by matthewmatician** [comment]
Thanks!
